import Head from 'next/head'
import Image from "next/image";
import Link from 'next/link'
import React from 'react';
import mementoImg from '../public/assets/projects/mindfulness.jpg'
import { RiRadioButtonFill } from 'react-icons/ri'

export default function Memento() {
  return (
    <div>
    <Head>
        <title>Jackson Howe | Memento</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/data-science.png" />
    </Head>
    <div className='w-full'>
      <div className='w-screen h-[30vh] lg:h-[40vh] relative'>
        <div className='absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/80 z-10' />
        <Image
          className='absolute z-l'
          src={mementoImg}
          alt='/'
          fill
          sizes="100vw"
          style={{
            objectFit: "cover"
          }} />
        <div className='absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2'>
          <h2 className='py-2'>Memento: Full-stack mindfullness Android app</h2>
          <h3>Kotlin / Jetpack Compose / Android Studio</h3>
        </div>
      </div>

        <div className='max-w-[1240px] mx-auto p-2 grid md:grid-col-5 gap-9 pt-8'>
          <div className='col-span-4'>
            <p>Project</p>
            <h2>Description</h2>
            <p className='mt-4'>
              In the winter semester of 2024, I worked on a team project to create a full-stack Android app called Memento that we published to the <a className='underline text-[#0A95FF]' href="https://play.google.com/store/apps/details?id=com.burgerbytes.memento&pcampaignid=web_share">Google Play Store</a>. As the semester-long project in CS456, software engineering, at the University of Waterloo, our group built a social mindfulness app that prompts users to write down a journal entry or take a picture of something beautiful. The goal of Memento is to create a welcoming community of individuals looking to undertake a mindfulness journey and improve their mental health.
            </p>
            <br></br>
            <p>
              Memento was built with <strong>Kotlin</strong>, using the <strong>Jetpack Compose</strong> framework and <strong>Android Studio</strong>. I lead application architecture efforts, designing the app components and deployment, accompanied by component, class, and deployment diagrams. I also worked on the “Discovery” page, designing and building the UI for that page, and implementing the scrolling and lazy loading features for the images. Hopefully our app helps you keep mementos of important life moments!
            </p>
            <button className='px-8 py-2 mt-4 mr-8 cursor-pointer hover:scale-110 ease-in duration-300'>
              <Link href="https://github.com/mgmavely/CS446-Group-11" >
                Code
              </Link>
            </button>
            <button className='px-8 py-2 mt-4 mr-8 cursor-pointer hover:scale-110 ease-in duration-300'>
              <Link href="https://play.google.com/store/apps/details?id=com.burgerbytes.memento&pcampaignid=web_share" >
                Google Play Store
              </Link>
            </button>
          </div>
          <div className='col-span-4 md:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4'>
            <div className='p-2'>
              <p className='text-center font-bold pb-2'>Technologies</p>
              <div className='grid grid-cols-3 md:grid-cols-1'>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />Kotlin</p>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />Jetpack Compose</p>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />Android Studio</p>
              </div>
            </div>
          </div>
          <Link href='/#projects'>
            <p className='underline cursor-poiner'>Back</p>
          </Link>
        </div>


    </div>
    </div>
  );
}