import Head from 'next/head';
import Image from "next/legacy/image";
import Link from 'next/link'
import React from 'react';
import primalityImg from '../public/assets/projects/enigma_machine.jpg'
import { RiRadioButtonFill } from 'react-icons/ri'

const primalityTesting = () => {
  return (
    <div>
    <Head>
        <title>Jackson Howe | Cryptography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/data-science.png" />
    </Head>
    <div className='w-full'>
      <div className='w-screen h-[30vh] lg:h-[40vh] relative'>
        <div className='absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/80 z-10' />
        <Image className='absolute z-l' layout='fill' objectFit='cover' src={primalityImg} alt='/' />
        <div className='absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2'>
          <h2 className='py-2'>Cryptography: Primality Testing</h2>
          <h3>Python</h3>
        </div>
      </div>

        <div className='max-w-[1240px] mx-auto p-2 grid md:grid-col-5 gap-9 pt-8'>
          <div className='col-span-4'>
            <p>Project</p>
            <h2>Description</h2>
            <p className='mt-4'>
              In the winter of 2022, I was a member of the <a className='underline text-[#0A95FF]' href="https://www.math.uwo.ca/undergraduate/current_students/directed_reading_program.html">Directed Reading Program</a> in the mathematics department at Western University. I researched primality testing algorithms, which underlie much of the cryptographic protocols of modern security systems, such as RSA encryption. The three algorithms I researched, implemented, and proved were <a className='underline text-[#0A95FF]' href="https://en.wikipedia.org/wiki/Fermat%27s_little_theorem">Fermat's Little Theorem</a>, the <a className='underline text-[#0A95FF]' href="https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes">Sieve of Eratosthenes</a>, and the <a className='underline text-[#0A95FF]' href="https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test">Miller-Rabin Test</a>. I implemented these algorithms in <strong>Python</strong>, and presented my work at the Western Undergraduate Reading Program Seminar on April 2, 2022.
            </p>
            <button className='px-8 py-2 mt-4 mr-8'>
                <Link href="https://github.com/JacksonH44/PrimalityTesting/tree/main">
                  Code
                </Link>
              </button>
          </div>
          <div className='col-span-4 md:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4'>
            <div className='p-2'>
              <p className='text-center font-bold pb-2'>Technologies</p>
              <div className='grid grid-cols-3 md:grid-cols-1'>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />Python</p>
              
              </div>
            </div>
          </div>
          <Link href='/#projects'>
            <p className='underline cursor-poiner'>Back</p>
          </Link>
        </div>


    </div>
    </div>
  )
}

export default primalityTesting;