import Head from 'next/head'
import Image from "next/image";
import Link from 'next/link'
import React from 'react';
import pmccImg from '../public/assets/projects/pmccrt.jpg'
import { RiRadioButtonFill } from 'react-icons/ri'

export default function DataPipeline() {
  return (
    <div>
    <Head>
        <title>Jackson Howe | University Health Network</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/data-science.png" />
    </Head>
    <div className='w-full'>
      <div className='w-screen h-[30vh] lg:h-[40vh] relative'>
        <div className='absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/80 z-10' />
        <Image
          className='absolute z-l'
          src={pmccImg}
          alt='/'
          fill
          sizes="100vw"
          style={{
            objectFit: "cover"
          }} />
        <div className='absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2'>
          <h2 className='py-2'>University Health Network</h2>
          <h3>Python / Github Actions / Docker / pytest / Pandas</h3>
        </div>
      </div>

        <div className='max-w-[1240px] mx-auto p-2 grid md:grid-col-5 gap-9 pt-8'>
          <div className='col-span-4'>
            <p>Project</p>
            <h2>Description</h2>
            <p className='mt-4'>
              In the summer of 2024, I worked for <a className='underline text-[#0A95FF]' href="https://www.uhn.ca/">University Health Network (UHN)</a>, engineering pipelines for data processing and analysis. I created data pipelines and visualization tools in <strong>Python</strong>, and designed and built fully autonomous continuous integration (CI) pipelines with <strong>Github Actions</strong>. The tool is also containerized with <strong>Docker</strong>. In addition to my technical work, I also organized a trivia night for UHN summer interns, with over 30 interns showing up for a fun night of questions, pizza, and conversation! I was also recognized with the Arthur Axelrad award for most outstanding summer student at the Princess Margaret Cancer Centre at UHN.
            </p>
            <br></br>
            <p>
              The data pipelines I worked on at UHN were in support of scientists researching protein-protein interactions. Engineering involved mining multiple bioinformatics databases for hundreds of features relating to thousands of proteins. A large contribution I made to the building of these pipelines was payload optimizations for calling these database APIs that reduced average API latency by 48%. I also created and executed over 50 unit tests using the <strong>pytest</strong> framework, and leveraged these tests to create a continuous integration pipeline with GitHub Actions for the tool.
            </p>
            <button className='px-8 py-2 mt-4 mr-8 cursor-pointer hover:scale-110 ease-in duration-300'>
              <Link href="https://github.com/JacksonH44/PPI-prediction">
                Code
              </Link>
            </button>
          </div>
          <div className='col-span-4 md:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4'>
            <div className='p-2'>
              <p className='text-center font-bold pb-2'>Technologies</p>
              <div className='grid grid-cols-3 md:grid-cols-1'>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />Python</p>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />Github Actions</p>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />Docker</p>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />pytest</p>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill className='pr-1' />Pandas</p>
              </div>
            </div>
          </div>
          <Link href='/#projects'>
            <p className='underline cursor-poiner'>Back</p>
          </Link>
        </div>


    </div>
    </div>
  );
}